In [1]:
import json

In [2]:
import urllib

In [3]:
import csv

In [4]:
import pandas as pd

In [5]:
import requests

In [7]:
import matplotlib.pyplot as plt

In [8]:
import numpy as np

In [9]:
import seaborn as sns
sns.set(color_codes=True)

In [10]:
import theano.tensor as tt
from matplotlib import gridspec
%matplotlib inline

ModuleNotFoundError: No module named 'theano'

In [10]:
all_state_ts_df = pd.read_csv("https://api.covidactnow.org/v2/states.timeseries.csv?apiKey=1540d77cf9a0422b88a2d90e989bbd23")
all_state_ts_df.info()
all_state_ts_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26942 entries, 0 to 26941
Data columns (total 40 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   date                                    26942 non-null  object
 1   country                                 26942 non-null  object
 2   state                                   26942 non-null  object
 3   county                                  0 non-null      float64
 4   fips                                    26942 non-null  int64
 5   lat                                     0 non-null      float64
 6   long                                    0 non-null      float64
 7   locationId                              26942 non-null  object
 8   actuals.cases                           26521 non-null  float64
 9   actuals.deaths                          26537 non-null  float64
 10  actuals.positiveTests                   25982 non-null  float64
 11  actuals.negativeTests                   26223 non-null  float64
 12  actuals.contactTracers                  22109 non-null  float64
 13  actuals.hospitalBeds.capacity           0 non-null      float64
 14  actuals.hospitalBeds.currentUsageTotal  15838 non-null  float64
 15  actuals.hospitalBeds.currentUsageCovid  15838 non-null  float64
 16  actuals.hospitalBeds.typicalUsageRate   0 non-null      float64
 17  actuals.icuBeds.capacity                15838 non-null  float64
 18  actuals.icuBeds.currentUsageTotal       15838 non-null  float64
 19  actuals.icuBeds.currentUsageCovid       15838 non-null  float64
 20  actuals.icuBeds.typicalUsageRate        0 non-null      float64
 21  actuals.newCases                        26379 non-null  float64
 22  actuals.vaccinesDistributed             9134 non-null   float64
 23  actuals.vaccinationsInitiated           9100 non-null   float64
 24  actuals.vaccinationsCompleted           9100 non-null   float64
 25  metrics.testPositivityRatio             25926 non-null  float64
 26  metrics.testPositivityRatioDetails      0 non-null      float64
 27  metrics.caseDensity                     26786 non-null  float64
 28  metrics.contactTracerCapacityRatio      21945 non-null  float64
 29  metrics.infectionRate                   25950 non-null  float64
 30  metrics.infectionRateCI90               25950 non-null  float64
 31  metrics.icuHeadroomRatio                15838 non-null  float64
 32  metrics.icuHeadroomDetails              0 non-null      float64
 33  metrics.icuCapacityRatio                15838 non-null  float64
 34  riskLevels.overall                      26942 non-null  int64
 35  metrics.vaccinationsInitiatedRatio      9100 non-null   float64
 36  metrics.vaccinationsCompletedRatio      9100 non-null   float64
 37  actuals.newDeaths                       26346 non-null  float64
 38  actuals.vaccinesAdministered            9134 non-null   float64
 39  riskLevels.caseDensity                  26942 non-null  int64
dtypes: float64(33), int64(3), object(4)
memory usage: 8.2+ MB

,date,country,state,county,fips,lat,long,locationId,actuals.cases,actuals.deaths,...,metrics.infectionRateCI90,metrics.icuHeadroomRatio,metrics.icuHeadroomDetails,metrics.icuCapacityRatio,riskLevels.overall,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,riskLevels.caseDensity
0,2020-03-01,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
1,2020-03-02,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
2,2020-03-03,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
3,2020-03-04,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
4,2020-03-05,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0

In [13]:
all_state_ts_df_MYSQL =pd.DataFrame(all_state_ts_df)
all_state_ts_df_MYSQL['date'] = pd.to_datetime(all_state_ts_df_MYSQL['date'])
all_state_ts_df_MYSQL['country'] = all_state_ts_df_MYSQL['country'].replace (np.nan, "")
all_state_ts_df_MYSQL['county'] = all_state_ts_df_MYSQL['county'].replace (np.nan, "")
all_state_ts_df_MYSQL['state'] = all_state_ts_df_MYSQL['state'].replace (np.nan, "")
all_state_ts_df_MYSQL['lat'] = all_state_ts_df_MYSQL['lat'].replace (np.nan, "")
all_state_ts_df_MYSQL['long'] = all_state_ts_df_MYSQL['long'].replace (np.nan, "")
all_state_ts_df_MYSQL['actuals.cases'] = all_state_ts_df_MYSQL['actuals.cases'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.deaths'] = all_state_ts_df_MYSQL['actuals.deaths'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.positiveTests'] = all_state_ts_df_MYSQL['actuals.positiveTests'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.negativeTests'] = all_state_ts_df_MYSQL['actuals.negativeTests'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.contactTracers'] = all_state_ts_df_MYSQL['actuals.contactTracers'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.hospitalBeds.capacity'] = all_state_ts_df_MYSQL['actuals.hospitalBeds.capacity'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.hospitalBeds.currentUsageTotal'] = all_state_ts_df_MYSQL['actuals.hospitalBeds.currentUsageTotal'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.hospitalBeds.currentUsageCovid'] = all_state_ts_df_MYSQL['actuals.hospitalBeds.currentUsageCovid'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.hospitalBeds.typicalUsageRate'] = all_state_ts_df_MYSQL['actuals.hospitalBeds.typicalUsageRate'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.icuBeds.capacity'] = all_state_ts_df_MYSQL['actuals.icuBeds.capacity'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.icuBeds.currentUsageTotal'] = all_state_ts_df_MYSQL['actuals.icuBeds.currentUsageTotal'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.icuBeds.currentUsageCovid'] = all_state_ts_df_MYSQL['actuals.icuBeds.currentUsageCovid'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.icuBeds.typicalUsageRate'] = all_state_ts_df_MYSQL['actuals.icuBeds.typicalUsageRate'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.newCases'] = all_state_ts_df_MYSQL['actuals.newCases'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.vaccinesDistributed'] = all_state_ts_df_MYSQL['actuals.vaccinesDistributed'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.vaccinationsInitiated'] = all_state_ts_df_MYSQL['actuals.vaccinationsInitiated'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.vaccinationsCompleted'] = all_state_ts_df_MYSQL['actuals.vaccinationsCompleted'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.testPositivityRatio'] = all_state_ts_df_MYSQL['metrics.testPositivityRatio'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.testPositivityRatioDetails'] = all_state_ts_df_MYSQL['metrics.testPositivityRatioDetails'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.caseDensity'] = all_state_ts_df_MYSQL['metrics.caseDensity'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.contactTracerCapacityRatio'] = all_state_ts_df_MYSQL['metrics.contactTracerCapacityRatio'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.infectionRate'] = all_state_ts_df_MYSQL['metrics.infectionRate'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.infectionRateCI90'] = all_state_ts_df_MYSQL['metrics.infectionRateCI90'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.icuHeadroomRatio'] = all_state_ts_df_MYSQL['metrics.icuHeadroomRatio'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.icuHeadroomDetails'] = all_state_ts_df_MYSQL['metrics.icuHeadroomDetails'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.icuCapacityRatio'] = all_state_ts_df_MYSQL['metrics.icuCapacityRatio'].replace (np.nan, 0)
all_state_ts_df_MYSQL['riskLevels.overall'] = all_state_ts_df_MYSQL['riskLevels.overall'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.vaccinationsInitiatedRatio'] = all_state_ts_df_MYSQL['metrics.vaccinationsInitiatedRatio'].replace (np.nan, 0)
all_state_ts_df_MYSQL['metrics.vaccinationsCompletedRatio'] = all_state_ts_df_MYSQL['metrics.vaccinationsCompletedRatio'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.newDeaths'] = all_state_ts_df_MYSQL['actuals.newDeaths'].replace (np.nan, 0)
all_state_ts_df_MYSQL['actuals.vaccinesAdministered'] = all_state_ts_df_MYSQL['actuals.vaccinesAdministered'].replace (np.nan, 0)
all_state_ts_df_MYSQL.info()
all_state_ts_df_MYSQL.head()
cols=",".join([str(i) for i in all_state_ts_df_MYSQL.columns.tolist()])
cols

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26942 entries, 0 to 26941
Data columns (total 40 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   date                                    26942 non-null  datetime64[ns]
 1   country                                 26942 non-null  object
 2   state                                   26942 non-null  object
 3   county                                  26942 non-null  object
 4   fips                                    26942 non-null  int64
 5   lat                                     26942 non-null  object
 6   long                                    26942 non-null  object
 7   locationId                              26942 non-null  object
 8   actuals.cases                           26942 non-null  float64
 9   actuals.deaths                          26942 non-null  float64
 10  actuals.positiveTests                   26942 non-null  float64
 11  actuals.negativeTests                   26942 non-null  float64
 12  actuals.contactTracers                  26942 non-null  float64
 13  actuals.hospitalBeds.capacity           26942 non-null  float64
 14  actuals.hospitalBeds.currentUsageTotal  26942 non-null  float64
 15  actuals.hospitalBeds.currentUsageCovid  26942 non-null  float64
 16  actuals.hospitalBeds.typicalUsageRate   26942 non-null  float64
 17  actuals.icuBeds.capacity                26942 non-null  float64
 18  actuals.icuBeds.currentUsageTotal       26942 non-null  float64
 19  actuals.icuBeds.currentUsageCovid       26942 non-null  float64
 20  actuals.icuBeds.typicalUsageRate        26942 non-null  float64
 21  actuals.newCases                        26942 non-null  float64
 22  actuals.vaccinesDistributed             26942 non-null  float64
 23  actuals.vaccinationsInitiated           26942 non-null  float64
 24  actuals.vaccinationsCompleted           26942 non-null  float64
 25  metrics.testPositivityRatio             26942 non-null  float64
 26  metrics.testPositivityRatioDetails      26942 non-null  float64
 27  metrics.caseDensity                     26942 non-null  float64
 28  metrics.contactTracerCapacityRatio      26942 non-null  float64
 29  metrics.infectionRate                   26942 non-null  float64
 30  metrics.infectionRateCI90               26942 non-null  float64
 31  metrics.icuHeadroomRatio                26942 non-null  float64
 32  metrics.icuHeadroomDetails              26942 non-null  float64
 33  metrics.icuCapacityRatio                26942 non-null  float64
 34  riskLevels.overall                      26942 non-null  int64
 35  metrics.vaccinationsInitiatedRatio      26942 non-null  float64
 36  metrics.vaccinationsCompletedRatio      26942 non-null  float64
 37  actuals.newDeaths                       26942 non-null  float64
 38  actuals.vaccinesAdministered            26942 non-null  float64
 39  riskLevels.caseDensity                  26942 non-null  int64
dtypes: datetime64[ns](1), float64(30), int64(3), object(6)
memory usage: 8.2+ MB

'date,country,state,county,fips,lat,long,locationId,actuals.cases,actuals.deaths,actuals.positiveTests,actuals.negativeTests,actuals.contactTracers,actuals.hospitalBeds.capacity,actuals.hospitalBeds.currentUsageTotal,actuals.hospitalBeds.currentUsageCovid,actuals.hospitalBeds.typicalUsageRate,actuals.icuBeds.capacity,actuals.icuBeds.currentUsageTotal,actuals.icuBeds.currentUsageCovid,actuals.icuBeds.typicalUsageRate,actuals.newCases,actuals.vaccinesDistributed,actuals.vaccinationsInitiated,actuals.vaccinationsCompleted,metrics.testPositivityRatio,metrics.testPositivityRatioDetails,metrics.caseDensity,metrics.contactTracerCapacityRatio,metrics.infectionRate,metrics.infectionRateCI90,metrics.icuHeadroomRatio,metrics.icuHeadroomDetails,metrics.icuCapacityRatio,riskLevels.overall,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,riskLevels.caseDensity'

In [23]:
all_state_ts_df_MYSQL.head(100)


all_state_ts_df_MYSQL.columns
all_state_ts_df_MYSQL.columns = all_state_ts_df_MYSQL.columns.str.replace("[.]", "_")
all_state_ts_df_MYSQL

/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  """

,date,country,state,county,fips,lat,long,locationId,actuals_cases,actuals_deaths,...,metrics_infectionRateCI90,metrics_icuHeadroomRatio,metrics_icuHeadroomDetails,metrics_icuCapacityRatio,riskLevels_overall,metrics_vaccinationsInitiatedRatio,metrics_vaccinationsCompletedRatio,actuals_newDeaths,actuals_vaccinesAdministered,riskLevels_caseDensity
0,2020-03-01,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
1,2020-03-02,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
2,2020-03-03,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
3,2020-03-04,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
4,2020-03-05,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26937,2021-07-12,US,WY,,56,,,iso1:us#iso2:us-wy,63138.0,751.0,...,0.17,0.0,0.0,0.0,2,0.403,0.357,0.0,434942.0,2
26938,2021-07-13,US,WY,,56,,,iso1:us#iso2:us-wy,63235.0,760.0,...,0.18,0.0,0.0,0.0,2,0.404,0.358,9.0,436027.0,2
26939,2021-07-14,US,WY,,56,,,iso1:us#iso2:us-wy,63331.0,760.0,...,0.18,0.0,0.0,0.0,2,0.404,0.358,0.0,436120.0,2
26940,2021-07-15,US,WY,,56,,,iso1:us#iso2:us-wy,63455.0,760.0,...,0.19,0.0,0.0,0.0,2,0.405,0.359,0.0,437278.0,2
26941,2021-07-16,US,WY,,56,,,iso1:us#iso2:us-wy,0.0,0.0,...,0.00,0.0,0.0,0.0,2,0.000,0.000,0.0,0.0,2

In [59]:
all_state_postgres = all_state_ts_df_MYSQL.reset_index().copy()

all_state_postgres = all_state_postgres.rename(columns={"index": "id"})
all_state_postgres.set_index("id", inplace=True) 
all_state_postgres.columns

Index(['date', 'country', 'state', 'county', 'fips', 'lat', 'long',
       'locationId', 'actuals_cases', 'actuals_deaths',
       'actuals_positiveTests', 'actuals_negativeTests',
       'actuals_contactTracers', 'actuals_hospitalBeds_capacity',
       'actuals_hospitalBeds_currentUsageTotal',
       'actuals_hospitalBeds_currentUsageCovid',
       'actuals_hospitalBeds_typicalUsageRate', 'actuals_icuBeds_capacity',
       'actuals_icuBeds_currentUsageTotal',
       'actuals_icuBeds_currentUsageCovid', 'actuals_icuBeds_typicalUsageRate',
       'actuals_newCases', 'actuals_vaccinesDistributed',
       'actuals_vaccinationsInitiated', 'actuals_vaccinationsCompleted',
       'metrics_testPositivityRatio', 'metrics_testPositivityRatioDetails',
       'metrics_caseDensity', 'metrics_contactTracerCapacityRatio',
       'metrics_infectionRate', 'metrics_infectionRateCI90',
       'metrics_icuHeadroomRatio', 'metrics_icuHeadroomDetails',
       'metrics_icuCapacityRatio', 'riskLevels_overall',
       'metrics_vaccinationsInitiatedRatio',
       'metrics_vaccinationsCompletedRatio', 'actuals_newDeaths',
       'actuals_vaccinesAdministered', 'riskLevels_caseDensity'],
      dtype='object')

In [60]:
all_state_postgres

,date,country,state,county,fips,lat,long,locationId,actuals_cases,actuals_deaths,...,metrics_infectionRateCI90,metrics_icuHeadroomRatio,metrics_icuHeadroomDetails,metrics_icuCapacityRatio,riskLevels_overall,metrics_vaccinationsInitiatedRatio,metrics_vaccinationsCompletedRatio,actuals_newDeaths,actuals_vaccinesAdministered,riskLevels_caseDensity
id,,,,,,,,,,,,,,,,,,,,,
0,2020-03-01,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
1,2020-03-02,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
2,2020-03-03,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
3,2020-03-04,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
4,2020-03-05,US,AK,,2,,,iso1:us#iso2:us-ak,0.0,0.0,...,0.00,0.0,0.0,0.0,0,0.000,0.000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26937,2021-07-12,US,WY,,56,,,iso1:us#iso2:us-wy,63138.0,751.0,...,0.17,0.0,0.0,0.0,2,0.403,0.357,0.0,434942.0,2
26938,2021-07-13,US,WY,,56,,,iso1:us#iso2:us-wy,63235.0,760.0,...,0.18,0.0,0.0,0.0,2,0.404,0.358,9.0,436027.0,2
26939,2021-07-14,US,WY,,56,,,iso1:us#iso2:us-wy,63331.0,760.0,...,0.18,0.0,0.0,0.0,2,0.404,0.358,0.0,436120.0,2
26940,2021-07-15,US,WY,,56,,,iso1:us#iso2:us-wy,63455.0,760.0,...,0.19,0.0,0.0,0.0,2,0.405,0.359,0.0,437278.0,2
26941,2021-07-16,US,WY,,56,,,iso1:us#iso2:us-wy,0.0,0.0,...,0.00,0.0,0.0,0.0,2,0.000,0.000,0.0,0.0,2

In [51]:
from sqlalchemy import create_engine

In [61]:
connection_string = "postgres:postgres@localhost:5433/covidfinaltestdb"
engine = create_engine(f'postgresql://{connection_string}')

In [62]:
engine.table_names()

['covid2']

In [63]:
all_state_postgres.to_sql(name='covid2', con=engine, if_exists='replace', index=True)